version: "3.8"

services:
  db:
    container_name: scribydb
    image: postgres:13-alpine
    restart: always
    ports:
      - "5446:5432"
    environment:
      - POSTGRES_USER=scribydb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - file_storage:/file_storage
volumes:
  db_data:
  file_storage:
